version: '3'

services:
  postgres:
    image: postgres:17.4
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=web
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    image: web
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    volumes:
      - .:/app
    ports:
      - 3001:3000
    depends_on:
      - postgres

